"""add column fiel exp

Revision ID: 7790d20dde04
Revises: 9cd3fc83b337
Create Date: 2019-03-11 17:13:24.060327

"""

# revision identifiers, used by Alembic.
revision = '7790d20dde04'
down_revision = '9cd3fc83b337'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_info', sa.Column('文件后缀', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_info', '文件后缀')
    # ### end Alembic commands ###
